easy_admin:
    entities:
        Trip:
            class: App\Entity\Trip
            list:
                fields:
                    - 'author'
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - 'author'
        User:
            class: App\Entity\User
            edit:
                item_permission: 'ROLE_HUMAN_RESOURCE'
            list:
                fields:
                    - {property: 'password', type: 'password'}