easy_admin:
    entities:
        Trip:
            class: App\Entity\Trip
            list:
                fields:
                    - {property: 'resource', type: 'image', base_path: 'public/uploads/images'}