nelmio_api_doc:
    documentation:
        info:
            title: "BackPackers"
            description: 'Find your trip'
            version: '1.0.0'
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc)