security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_SUPER_ADMIN:       [ROLE_ADMIN, ROLE_IMPERSONATOR]
        ROLE_ADMIN:             [ROLE_MODERATOR, ROLE_HUMAN_RESOURCES]
        ROLE_MODERATOR:         ROLE_EDITOR
        ROLE_GUIDE:             ROLE_USER
        ROLE_HUMAN_RESURCES:    ROLE_USER
        ROLE_USER_MOBILE:       ROLE_USER

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            switch_user: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
         - { path: ^/dashboard, roles: ROLE_USER }
         - { path: ^/profile, roles: ROLE_USER }
         - { path: ^/imguide, roles: ROLE_USER }
