version: '2.1'
services:
    nginx:
        container_name: rbac.nginx
        build: ./docker/nginx
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/logs:/var/log/nginx
            - ./:/var/www
        links:
            - php
        networks:
            - docker
    php:
        container_name: rbac.php
        user: serhii
        build: ./docker/php
        tty: true
        links:
            - db
        volumes:
            - ./:/var/www
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - docker
    db:
        container_name: rbac.db
        image: postgres:latest
        environment:
            POSTGRES_USER: rbac_docker
            POSTGRES_PASSWORD: rbac_docker
            POSTGRES_DB: rbac_docker
        restart: always
        command: postgres -c port=5432
        ports:
            - 15432:5432
        networks:
            - docker
networks:
    docker:
        driver: bridge
        ipam:
            config:
                -   subnet: 195.168.0.100/27
                    gateway: 195.168.0.101