version: '3'
services:
    nginx:
        container_name: rbac.nginx
        image: nginx:latest
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
            - ./:/var/www
        links:
            - php
    php:
        container_name: rbac.php
        user: serhii
        ports:
            - "9000:9000"
        build: ./docker/php
        tty: true
        links:
            - db
        volumes:
            - ./:/var/www
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    db:
        container_name: rbac.db
        image: postgres:latest
        environment:
            POSTGRES_USER: rbac_docker
            POSTGRES_PASSWORD: rbac_docker
            POSTGRES_DB: rbac_docker
        restart: always
        command: postgres -c port=5432
        ports:
            - 15432:5432